### ISSUE TITLE
Upgrade to mongodb 2.x

### ISSUE THREAD

**Issue by patrickfreed** [kebasyaty/green-barrel#56]
The `mongodb` crate released its 2.0.0 version just over a year ago, and the 1.x branch hasn't been receiving any new features since then. Soon, the 1.x versions of the driver will be EOL and won't receive any bug fixes either. For these reasons, this crate should update its dependency on `mongodb` to 2.x.

See https://github.com/mongodb/mongo-rust-driver/releases/tag/v2.0.0 for information on how to migrate.

**Comment by kebasyaty** [comment]
Yes, I know that mongodb v2 was released.
I wanted the second version to insist like good and expensive wine.
Your message means that the time for change has come.
Thank you.
